name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Execute remote SSH using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            git clone https://github.com/tejas-0-0-7/Github_Acrtions.git
            cd ~/Github_Acrtions
            docker compose pull
            docker compose up -d