name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Execute remote SSH using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            if [ -d ~/Github_Acrtions ]; then
              cd ~/Github_Acrtions
              git pull
            else
              git clone https://github.com/tejas-0-0-7/Github_Acrtions.git ~/Github_Acrtions
              cd ~/Github_Acrtions
            fi
            docker compose pull
            docker compose up -d